{{- $debugPod := .Values.debugPod -}}
{{ if $debugPod }}
---
apiVersion: v1
kind: Pod
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.debugPodName }}
  labels:
    type: 'cron'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  containers:
  - command:
    - {{ .Values.debugCommand }}
{{ if .Values.debugCommandArgs }}
    args:
{{- with .Values.debugCommandArgs -}}
{{ toYaml . | nindent 6 }}
{{ end }}
{{ end }}
{{ if .Values.useResourcesLimits }}
    resources:
      requests:
        memory: '{{ .Values.requestsMemory }}'
        cpu: '{{ .Values.requestsCPU }}'
      limits:
        memory: '{{ .Values.limitsMemory }}'
        cpu: '{{ .Values.limitsCPU }}'
{{ end }}
    env:
    - name: SDS_DEBUG
      value: '{{ .Values.sdsDebug }}'
    - name: SDS_CMDDEBUG
      value: '{{ .Values.sdsCmdDebug }}'
    - name: SDS_ST
      value: '{{ .Values.sdsST }}'
    - name: SDS_NCPUS
      value: '{{ .Values.sdsNCPUs }}'
    - name: SDS_CTXOUT
      value: '{{ .Values.sdsCtxOut }}'
    - name: SDS_SKIPTIME
      value: '{{ .Values.sdsSkipTime }}'
    - name: SH_USER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.shSecret }}
          key: SH_USER.secret
    - name: SH_HOST
      valueFrom:
        secretKeyRef:
          name: {{ .Values.shSecret }}
          key: SH_HOST.secret
    - name: SH_PORT
      valueFrom:
        secretKeyRef:
          name: {{ .Values.shSecret }}
          key: SH_PORT.secret
    - name: SH_PASS
      valueFrom:
        secretKeyRef:
          name: {{ .Values.shSecret }}
          key: SH_PASS.secret
    - name: SH_DB
      valueFrom:
        secretKeyRef:
          name: {{ .Values.shSecret }}
          key: SH_DB.secret
    - name: SDS_ES_URL
      valueFrom:
        secretKeyRef:
          name: {{ .Values.esSecret }}
          key: ES_URL.secret
    - name: ZIPPASS
      valueFrom:
        secretKeyRef:
          name: {{ .Values.zipSecret }}
          key: ZIPPASS.secret
    image: '{{ .Values.debugImage }}-{{ .Values.deployEnv }}'
    imagePullPolicy: {{ .Values.imagePullPolicy }}
    name: {{ .Values.debugPodName }}
  restartPolicy: {{ .Values.imageRestartPolicy }}
{{ if .Values.useNodeSelector }}
  nodeSelector:
{{- with .Values.nodeSelector -}}
{{ toYaml . | nindent 4 }}
{{ end }}
{{ end }}
{{ end }}
