{{- $skipPV := .Values.skipPV -}}
{{ if not $skipPV }}
{{- $root := . -}}
{{- $nodeIdx := .Values.nodeIdx -}}
{{- range $nIdx := untilStep 0 (.Values.nodeNum|int) 1 -}}
{{ if or (not $nodeIdx) (eq $nIdx ($nodeIdx|int)) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: '{{ $root.Values.namespace }}'
  name: '{{ $root.Values.pvName }}-{{ $nIdx }}'
  labels:
    type: pvc
{{- with $root.Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/instance: sds
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sds
spec:
  accessModes:
    - {{ $root.Values.pvAccessMode }}
  storageClassName: {{ $root.Values.pvStorageClass }}
  resources:
    requests:
      storage: {{ $root.Values.pvSize }}
{{ end }}
{{ end }}
{{ end }}
