{{- $skipSecrets := .Values.skipSecrets -}}
{{ if not $skipSecrets }}
{{- $skipSHSecret := .Values.skipSHSecret -}}
{{ if not $skipSHSecret }}
# SH secret starts
{{- $shUser := or .Values.shUser (.Files.Get "secrets/SH_USER.secret") -}}
{{- $shHost := or .Values.shHost (.Files.Get (printf "secrets/SH_HOST.%s.secret" .Values.deployEnv)) -}}
{{- $shPort := or .Values.shPort (.Files.Get "secrets/SH_PORT.secret") -}}
{{- $shPass := or .Values.shPass (.Files.Get (printf "secrets/SH_PASS.%s.secret" .Values.deployEnv)) -}}
{{- $shDB := or .Values.shDB (.Files.Get "secrets/SH_DB.secret") -}}
{{ if and $shUser $shHost $shPort $shPass $shDB }}
---
apiVersion: v1
data:
  SH_USER.secret: {{ $shUser | b64enc }}
  SH_HOST.secret: {{ $shHost | b64enc }}
  SH_PORT.secret: {{ $shPort | b64enc }}
  SH_PASS.secret: {{ $shPass | b64enc }}
  SH_DB.secret: {{ $shDB | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.shSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_one_or_more_sh_secrets: "Please take a look at the NOTES.txt file"
{{ end }}
# SH secret ends
{{ end }}
{{- $skipESSecret := .Values.skipESSecret -}}
{{ if not $skipESSecret }}
# ES secret starts
{{- $esURL := or .Values.esURL (.Files.Get "secrets/ES_URL.secret") -}}
{{ if $esURL }}
---
apiVersion: v1
data:
  ES_URL.secret: {{ $esURL | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.esSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_es_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# ES secret ends
{{ end }}
{{- $skipZipSecret := .Values.skipZipSecret -}}
{{ if not $skipZipSecret }}
# ZIP secret starts
{{- $zipPass := or .Values.zipPass (.Files.Get "secrets/ZIPPASS.secret") -}}
{{ if $zipPass }}
---
apiVersion: v1
data:
  ES_URL.secret: {{ $zipPass | b64enc }}
kind: Secret
metadata:
  namespace: '{{ .Values.namespace }}'
  name: {{ .Values.zipSecret }}
  labels:
    type: 'secret'
{{- with .Values.labels -}}
{{ toYaml . | nindent 4 }}
{{ end }}
    app.kubernetes.io/name: {{ include "sds-helm.name" . }}
    helm.sh/chart: {{ include "sds-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: {{ .Values.secretType }}
{{ else }}
missing_zip_secret: "Please take a look at the NOTES.txt file"
{{ end }}
# ZIP secret ends
{{ end }}
{{ end }}
