# Secrets that can be set via files in `./secrets/*.secret`, via commandline by `--set 'shUser=xyz,shHost=host.com,...'` or even uncomment them in the lines below.
# shUser: ''
# shHost: ''
# shPort: ''
# shPass: ''
# shDB: ''
# esURL: ''
# zipPass: ''
# githubOAuth: ''
# repoAccess: ''
#
# You can skip some parts of the deployment (useful when deploying partailly again)
# skipCron (will not create a new cron job, you should set it when cron job is already created, if you want to recreate a cron job, delete the existing one first and do not set this flag)
# skipSecrets (will not attempt to create secrets, if you want to create new secrets delete current secrets first and do not set this flag)
# skipSHSecret (will skip creating SH (sorting hat) secret)
# skipESSecret (will skip creating ES (ElasticSearch) secret)
# skipZipSecret (will skip creating ZIP file password secret)
# skipGithubSecret (will skip creating GitHub file password secret)
# skipRepoSecret (will skip creating repo access secret)
# skipNamespace (will skip sds namespace creation)
# skipPV (will skip persistent volume creation)
#
# skipCron: 1
# skipSecrets: 1
# skipSHSecret: 1
# skipESSecret: 1
# skipZipSecret: 1
# skipGithubSecret: 1
# skipNamespace: 1
# skipRepoSecret: 1
# skipPV: 1
#
# sync-data-sources binary Environmental options (see README.md or NOTES.txt)
#
# sdsMaxRetry (Try to run grimoire stack (perceval, p2o.py etc) that many times before reporting failure, default 3)
# sdsDebug (Debug level: 0-no, 1-info, 2-verbose)
# sdsCmdDebug (Commands execution Debug level: 0-no, 1-only output commands, 2-output commands and their output, 3-output full environment as well, default)
# sdsST (force using single-threaded version)
# sdsNCPUs (set to override number of CPUs to run, this overwrites `SDS_ST`, default 0 (which means autodetect))
# sdsCtxOut (output all context data (configuration struct))
# sdsSkipTime (do not output time with log messages)
#
# sdsMaxRetry: 4
# sdsDebug: '2'
# sdsCmdDebug: '2'
# sdsST: 1
# sdsNCPUs: 16
# sdsCtxOut: '1'
# sdsSkipTime: 'y'
#
# Other evrironment options:
# esURL: 'http://127.0.0.1:9200'
# esBulkSize: '10000'
# schedule: '36 * * * *'
# syncCommandArgs:
#   - "bootarg"
# nodeNum: 3
# nodeIdx: 0
# nodeHash: '1'
# dryRun: '1'
# dryRunCode: '4'
# dryRunSeconds: '1'
# timeoutSeconds: '72000'
# nLongest: '30'
# skipSH: '1'
# stripErrorSize: '4096'
# useRepoAccess: ''
# latestItems: ''
# scrollWait: '30'
# silent: 'y'

# Standard values:
deployEnv: 'set-me'
dryRun: ''
dryRunCode: ''
dryRunSeconds: ''
timeoutSeconds: ''
nLongest: ''
skipSH: ''
stripErrorSize: ''
esURL: ''
esBulkSize: ''
scrollWait: ''
silent: ''
useRepoAccess: '1'
concurrencyPolicy: Forbid
fullnameOverride: sds
imagePullPolicy: Always
latestItems: ''
syncCommand: './run.sh'
syncImage: 'lukaszgryglicki/sync-data-sources'
syncPodName: sds
syncRestartPolicy: Never
limitsCPU: 48000m
limitsMemory: 256Gi
requestsCPU: 1000m
requestsMemory: 2Gi
name: sds
namespace: sds
nameOverride: sds
schedule: '0 0,3,6,9,12,15,18,21 * * *'
secretType: Opaque
shSecret: sh-db
esSecret: es-db
zipSecret: zip-pass
githubSecret: github-oauth
repoSecret: repo-secret
pvName: sds
pvAccessMode: ReadWriteOnce
pvStorageClass: openebs-hostpath
pvSize: 100Gi
pvMountPath: '/root/.perceval'
useResourcesLimits: ''
nodeHash: ''
nodeNum: 1
labels:
  name: sds
useNodeSelector: '1'
nodeSelector:
  lfda: grimoire
debugPod: ''
debugPodName: 'sds-debug'
debugCommand: '/bin/sleep'
debugCommandArgs: ['36525d']
debugImage: 'lukaszgryglicki/sync-data-sources'
